### ISSUE TITLE
Issue on linux - input file at scraper.py line6

### ISSUE THREAD

**Issue by imranget** [hardeepnarang10/fb2ics#3]
Error message saying that the input file is not found. Hardcoding the name of the file in line 6 of the scraper.py file makes it work e.g. 
```

def scrape_line_selector(file_name):
    html_file = open("_/home/imran/Desktop/fb_parse/fb2ics-master/resources/Events2.html_", mode='r', encoding="utf-8")

```

**Comment by hardeepnarang10** [comment]
**Version 1.1.0** had path resolution for legacy DOS (Windows directory structure). Linux uses UNIX file system which has different path resolution (In simple terms: **back slashes** vs **forward slashes**).

I've made changes to **[fetch_html.py](../blob/master/include/fetch_html.py)** which takes care of cross-platform discrepancy.

**Remarks**:
Version jump: v1.1.0 to v2.0.0.
See **[commit history](../commits/master)**.

Thank you for reporting @imranget 
This issue has been resolved.
