### ISSUE TITLE
Bug with unicode characters

### ISSUE THREAD

**Issue by julien-tmp** [hardeepnarang10/fb2ics#5]
Hello,
First of all, thank you very much for helping us all with this script!

I executed it and I get the error below:
```
Executing fb2ics...
Traceback (most recent call last):
  File "fb2ics.py", line 122, in <module>
    main()
  File "fb2ics.py", line 73, in main
    calendar_file.writelines(parsed_output)
  File "C:\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0142' in position 13: character maps to <undefined>
Press any key to exit.
```

Would it be easy to fix?

**Comment by hardeepnarang10** [comment]
Just fixed. See commit (e86ea13).

Description: ICS module has 'cp1252' encoding by default. This was causing issue with special characters (some people for some reason include diacritical characters ( e.g: À, à) in their names).

File encoding set to 'utf-8' solved this issue.

Thanks for pointing it out @julien-tmp
