### ISSUE TITLE
empty ics file

### ISSUE THREAD

**Issue by schealex** [hardeepnarang10/fb2ics#8]
i just tried to use this tool but it just gives me a empty (part of the definitions) ics file with no entries whatsoever.

Steps
1. clone repo
2. save facebook birthdays (scrolled to november 2020) as Veranstaltungen.html in resources
3. run Installer_Windows.bat

**Comment by hardeepnarang10** [comment]
@schealex I need the HTML file to resolve this. Can you [mail it to me](mailto:hardeepnarang10@gmail.com)?

**Comment by schealex** [comment]
i'm afraid i cant do that because of data privacy reasons.
if you need spefific information i can try to provide those.
btw. the missing entries file does have one entry logged.

**Comment by hardeepnarang10** [comment]
Copy the entry in missing entries log. Search for this entry in your HTML file. There on, try deleting this entry from your HTML along with any spaces or carriage return that follow. For example:

```
foo content="missing_entry"

somecontent data="..."
```
becomes:

`foo somecontent data="..."`

Notice that I removed:
```
content="missing_entry"

``` 
and the carriage return that follows.

**Comment by hardeepnarang10** [comment]
@schealex Can you give an update? This thread is pending closure.
